// controllers/cityController.js

const asyncHandler = require("../middlewares/asyncHandler");
const { sendSuccess } = require("../utils/response");

const muzaffarpurCities = [
  "Kanti Chowk",
  "Pansalva Chowk",
  "Tenghrarai Chowk",
  "Bhanghara Chowk",
  "Mithanpura Chowk",
  "Juran Chapra Chowk",
  "Akhara Ghat Chowk",
  "Ramna Chowk",
  "Saraiyaganj Chowk",
  "Brahmpura Chowk",
  "Chaturbhuj Sthan Chowk",
  "Dahi Chowk",
  "Station Chowk",
  "Tower Chowk",
  "Motijheel Chowk",
  "Club Road Chowk",
  "Ahiyapur Chowk",
  "Bela Road Chowk",
  "Bhagwanpur Chowk",
  "Nathnagar Chowk",
  "Mushahari Chowk",
  "Balughat Chowk",
  "Shivaji Nagar Chowk",
  "Bairiya Chowk",
  "Sharif Nagar Chowk",
  "Kali Sthan Chowk",
  "Gola Road Chowk",
  "Umanagar Chowk",
  "Agamkuan Chowk",
  "Banjaria Chowk",

  "Motipur Chowk",
  "Gaighat Chowk",
  "Katra Chowk",
  "Sakra Chowk",
  "Paru Chowk",
  "Bochahan Chowk",
  "Minapur Chowk",
  "Aurai Chowk",
  "Kurhani Chowk",
  "Marwan Chowk",
  "Sahebganj Chowk",
  "Turki Chowk",
  "Muraul Chowk",
  "Maniyari Chowk",
  "Dholi Chowk",
  "Baruraj Chowk",
  "Majorganj Chowk",
  "Bandra Chowk",

  "Mithanpura",
  "Brahmpura",
  "Juran Chapra",
  "Saraiyaganj",
  "Ramna",
  "Motijheel",
  "Ahiyapur",
  "Balughat",
  "Mushahari",
  "Shivaji Nagar",
  "Gola Road",
  "Nathnagar",
  "Bela Road",
  "Bairiya",
  "Umanagar",
  "Kali Sthan",
  "Agamkuan",
  "Sharif Nagar",
  "Chaturbhuj Sthan",
  "Akhara Ghat",

  "Banjaria",
  "Bhagwanpur",
  "Chainpur",
  "Sirsia",
  "Pandaul",
  "Parsauni",
  "Bidupur",
  "Sarauni",
  "Koilakh",
  "Nariyar",
  "Gausfpur",
  "Rampur Dumra",
  "Bakhari",
  "Kamtaul",
  "Mishrauli",
  "Ramnagar",
  "Darbhanga Road",
];

const getCities = asyncHandler(async (req, res) => {
  return sendSuccess(res, 200, "Cities fetched successfully", {
    cities: muzaffarpurCities,
  });
});

module.exports = {
  getCities,
};